title = "CNI"
disableKinds = ["taxonomy", "taxonomyTerm"]

enableGitInfo = true

[markup.highlight]
style = "paraiso-dark"

[params]
projectName = "CNI"
font_awesome_version = "5.12.0"
description = "The Container Network Interface"
favicon = "favicon.png"
repositoryUrl = "https://github.com/containernetworking/cni.dev"
contentDir = "/content/"
cni_versions = ["0.4.0", "0.3.1", "0.3.0", "0.2.0", "0.1.0"]

[params.logos]
navbar = "cni-horizontal-color.png"

[[params.social]]
name = "GitHub"
color = "#000000"
url = "https://github.com/containernetworking"
icon = "fab fa-github"

[[params.social]]
name = "Twitter"
color = "#00aced"
url = "https://twitter.com/CloudNativeFdn"
icon = "fab fa-twitter"

[[params.fonts]]
name = "Fira Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Fira Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[[params.fonts]]
name = "Fire Sans"
sizes = [100, 200, 300, 400, 500, 600, 700]
type = "heading_font"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "CNI"
url = "/cni/"
weight = 2

